### ISSUE TITLE
Use constants

### ISSUE THREAD

**Issue by incredibleLeitman** [thirdiblind/High-LowNumberGuessing#1]
For the amount of guesses
https://github.com/thirdiblind/High-LowNumberGuessing/blob/60c9bf90d4f8b3c6fa059ffe11a651c16f3527b5/High-LowNumberGuessing/Program.cs#L9

but also the generated numbers.
(0 could be interpreted as an exception here, because it is very much read and interpretable)

This way you have exactly *one* place that defines the behavior of your program :D

**Comment by mayisa87** [comment]
And here too, define a constant for your max offset 5


https://github.com/thirdiblind/High-LowNumberGuessing/blob/bf731e58dbbc88267f97155aecb85ea1e5797d81/High-LowNumberGuessing/Program.cs#L26
