### ISSUE TITLE
Does this really need to be within an else branch?

### ISSUE THREAD

**Issue by incredibleLeitman** [thirdiblind/High-LowNumberGuessing#2]
https://github.com/thirdiblind/High-LowNumberGuessing/blob/60c9bf90d4f8b3c6fa059ffe11a651c16f3527b5/High-LowNumberGuessing/Program.cs#L25

Because once the user hits the right number, the loop breaks and the following code is not executed anyway.
Having less intendations makes code mich more readable

**Comment by mayisa87** [comment]
Related commit 651188d

**Comment by mayisa87** [comment]
This is not yet fully fixed. You delted the else, but added an if. 

https://github.com/thirdiblind/High-LowNumberGuessing/blob/bf731e58dbbc88267f97155aecb85ea1e5797d81/High-LowNumberGuessing/Program.cs#L24

As Michael wrote above, the code will break if the user guessed right. And you can be sure that the guessesRemaining is greater than zero, as this is already checked within your while condition too. 
So each time, each iteration, the while condition is again checked, and loop only entered, if this condition is OK. So not necessary to check it at this place again.

**Comment by incredibleLeitman** [comment]
Hey @thirdiblind you need to take care of the exact line numbers mentioned in the issue comments ☝️ 

The explanation @mayisa87 gave was referring to the condition *within* the loop: go through each step in your mind counting the remainingGuesses -> you start with 5, then all the checking happens, ..., 4, 3, 2, 1 -> this is the last time the loop body gets executed, and if the user guess the correct number the loop breaks (with guessesRemaining still having the value 1), if not the console output for close/higher/lower gets printed. Then the loop variable gets decreased by 1, reaching 0 and in the next step gets checked by the loop conditon "while (remainingGuesses > 0)". This evaluates to false (because the value *is not* greater than 0) so the loop breaks.


However, your change to this issue modified the behaviour of your program, so that even if the user has guessed the right value it gets printed "Sorry, you've run out of guesses."
