### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by incredibleLeitman** [thirdiblind/High-LowNumberGuessing#3]
https://github.com/thirdiblind/High-LowNumberGuessing/blob/60c9bf90d4f8b3c6fa059ffe11a651c16f3527b5/High-LowNumberGuessing/Program.cs#L36
https://github.com/thirdiblind/High-LowNumberGuessing/blob/60c9bf90d4f8b3c6fa059ffe11a651c16f3527b5/High-LowNumberGuessing/Program.cs#L41

Maybe you could move this line out of the two conditions?

**Comment by mayisa87** [comment]
Closed with ebd20c0
