### ISSUE TITLE
What is this used for?

### ISSUE THREAD

**Issue by incredibleLeitman** [thirdiblind/High-LowNumberGuessing#4]
https://github.com/thirdiblind/High-LowNumberGuessing/blob/60c9bf90d4f8b3c6fa059ffe11a651c16f3527b5/High-LowNumberGuessing/Program.cs#L1

If you dont actually wanted to include this using, remove it.

You can also let visual studio automatically take care of unused using by right clicking the using-block and select "remove and sort usings" or pressing the configured shortcut (usually Ctrl+K+D on windows)

**Comment by mayisa87** [comment]
Closed with bf731e5
